[package]
name = "generate_ast"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = "0.1.14"
proc-macro2 = "1.0.28"
quote = "1.0.9"
ungrammar = "1.14.4"

stdx = { path = "../stdx" }