[package]
name = "ide_diagnostics"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.0"

syntax = { path = "../syntax" }
ide_db = { path = "../ide_db" }
